all: sigdemo sigkill sigchild 
sigdemo:
	gcc sigdemo.c -o sigdemo
sigkill:
	gcc sigkill.c -o sigkill
sigchild:
	gcc sigchild.c -o sigchild
clean:
	 rm -f *.o   
	 rm -f sigdemo sigkill sigchild
	 rm -f *~
