all: pipes typeclient typeserver
pipes:
	gcc pipes.c -o pipes
typeclient:
	gcc typeclient.c -o typeclient
typeserver:
	gcc typeserver.c -o typeserver
clean:
	 rm -f *.o   
	 rm -f pipes typeclient typeserver
	 rm -f *~
